services:
  - type: web
    name: mylittlebank-app
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: mylittlebank-db
          property: connectionString

databases:
  - name: mylittlebank-db
    databaseName: mylittlebank
    plan: free